configMapGenerator:
- files:
  - application.yml
  name: 82265611-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "82265611"
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82265611
  newTag: latest
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202411130716"
